### ISSUE TITLE
Print unwrapped help description and epilog

### ISSUE THREAD

**Issue by serenity4** [zachmatson/ArgMacros.jl#5]
Hi,

First of all thanks for your work on this package. I really love its ease of use and performance (compared to ArgParse for example) and is very nice for quick CLI scripts.

I noticed that description and epilog texts are printed with `println_wrapped`, which produces big blocks of text. The main inconvenient is that newlines are ignored, so big help strings cannot be broken down into more readable chunks. Could it be printed the same as for the usage (i.e. with `println`)? What was the reason for using `println_wrapped`? I can make the PR if desired, it's just 2 line changes.

**Comment by zachmatson** [comment]
Thank you! I'm glad you enjoy using it.

I have gone back and forth on how I feel about wrapping it. Part of it was just because ArgParse wraps it, and on the actual argument descriptions it seems nice to have wrapping. I guess using the wrapped print for argument descriptions but leaving the main description and epilog unwrapped seems fair to me. Feel free to submit the PR, I will also need to look through the documentation to see if there is any reference to text wrapping that needs to be removed/updated.
